version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - ENVIRONMENT=docker
      - PORT=4000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=verifier
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=verifier
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
